"""
node_Group -> meta_group / link.label -> meta_relation 對照。
依真實資料 (data/_build_report.json) 統計後手動歸類；未對照值 fallback 到「其他」。
"""

# 7 個 meta_group
META_GROUPS = [
    "人物",
    "組織",
    "地景與聚落",
    "事件",
    "物質文化",
    "文獻",
    "計畫與行動",
    "其他",
]

META_GROUP_COLORS = {
    "人物":       "#4A6B5B",
    "組織":       "#6B5B7B",
    "地景與聚落": "#8B5A2B",
    "事件":       "#A8412B",
    "物質文化":   "#9B7B3F",
    "文獻":       "#7B6B5B",
    "計畫與行動": "#5E7B8C",
    "其他":       "#9C9180",
}

NODE_GROUP_TO_META = {
    # 人物
    "人物": "人物",
    "核心人物": "人物",
    "歷史人物": "人物",
    "族群": "人物",
    "民族": "人物",

    # 組織
    "政府機關": "組織",
    "政府機構": "組織",
    "非營利組織": "組織",
    "非營利組織（NPO）": "組織",
    "私人企業": "組織",
    "企業": "組織",
    "大學": "組織",
    "學校": "組織",
    "教會": "組織",
    "合作社": "組織",
    "工作室": "組織",
    "團隊": "組織",
    "機構": "組織",
    "組織": "組織",
    "公司": "組織",

    # 地景與聚落
    "部落": "地景與聚落",
    "地理位置": "地景與聚落",
    "聚落": "地景與聚落",
    "古道": "地景與聚落",
    "山系": "地景與聚落",
    "河流": "地景與聚落",
    "地名": "地景與聚落",
    "地點": "地景與聚落",
    "地區": "地景與聚落",
    "地景": "地景與聚落",
    "建築": "地景與聚落",
    "區域": "地景與聚落",

    # 事件
    "大事件": "事件",
    "事件": "事件",
    "歷史事件": "事件",
    "政策": "事件",
    "戰役": "事件",
    "活動": "事件",
    "災害": "事件",
    "健康問題": "事件",
    "疾病": "事件",
    "問題": "事件",

    # 物質文化
    "物件": "物質文化",
    "食物": "物質文化",
    "工藝": "物質文化",
    "工具": "物質文化",
    "農作物": "物質文化",
    "產業": "物質文化",
    "儀式": "物質文化",
    "口傳": "物質文化",
    "語言": "物質文化",
    "觀念": "物質文化",
    "知識": "物質文化",
    "技術": "物質文化",
    "信仰": "物質文化",

    # 文獻
    "文獻": "文獻",
    "論文": "文獻",
    "報告": "文獻",
    "書籍": "文獻",
    "紀錄片": "文獻",
    "影片": "文獻",
    "媒體": "文獻",
    "資料": "文獻",
    "歌曲": "文獻",
    "出版品": "文獻",

    # 計畫與行動
    "計畫": "計畫與行動",
    "課程": "計畫與行動",
    "教案": "計畫與行動",
    "尋根活動": "計畫與行動",
    "工作坊": "計畫與行動",
    "USR": "計畫與行動",
    "方案": "計畫與行動",
    "行動": "計畫與行動",
    "活動方案": "計畫與行動",
}


# 5 種 meta_relation
META_RELATIONS = ["spatial", "social", "causal", "creative", "documentary", "其他"]

META_RELATION_COLORS = {
    "spatial":     "#8B5A2B",
    "social":      "#4A6B5B",
    "causal":      "#A8412B",
    "creative":    "#6B5B7B",
    "documentary": "#7B6B5B",
    "其他":         "#9C9180",
}

LABEL_TO_META_RELATION = {
    # ─── spatial（位置/分布/路徑）─────────────────
    "空間關係": "spatial",
    "地理位置": "spatial",
    "位置": "spatial",
    "所在地": "spatial",
    "居住地": "spatial",
    "出生地": "spatial",
    "出生地/家鄉": "spatial",
    "出身地": "spatial",
    "家鄉": "spatial",
    "鄰近": "spatial",
    "經過": "spatial",
    "位於": "spatial",
    "起源於": "spatial",
    "遷徙": "spatial",
    "遷徙路徑": "spatial",
    "分布": "spatial",
    "分布地": "spatial",
    "產業分布": "spatial",
    "產業區域": "spatial",
    "走讀路線": "spatial",
    "尋根目的地": "spatial",
    "尋根路線": "spatial",
    "實施場域": "spatial",
    "執行場域": "spatial",
    "在地組織": "spatial",
    "在地學校": "spatial",
    "開闢": "spatial",
    "開發": "spatial",
    "包含": "spatial",
    "範圍": "spatial",

    # ─── social（人際/關係/從屬）─────────────────
    "人際關係": "social",
    "親屬": "social",
    "家族": "social",
    "伴侶": "social",
    "配偶": "social",
    "師承": "social",
    "師徒": "social",
    "合作": "social",
    "合作夥伴": "social",
    "夥伴": "social",
    "同事": "social",
    "領導": "social",
    "成員": "social",
    "代表": "social",
    "嚮導": "social",
    "文化嚮導": "social",
    "聯姻": "social",
    "參與": "social",
    "參與者": "social",
    "介入對象": "social",
    "服務對象": "social",
    "受益者": "social",
    "事件當事人": "social",
    "主要人物": "social",
    "發起/帶隊": "social",
    "發起": "social",
    "帶隊": "social",
    "創辦人": "social",
    "創辦": "social",
    "共同創辦": "social",
    "創立": "social",
    "成立": "social",
    "傳承": "social",
    "傳承者": "social",
    "生活模式": "social",
    "個人觀點": "social",
    "社會服務": "social",
    "業態關聯": "social",

    # ─── causal（因果/影響/政策）─────────────────
    "政策推動": "causal",
    "推動": "causal",
    "推廣": "causal",
    "影響": "causal",
    "正面影響": "causal",
    "負面影響": "causal",
    "改善": "causal",
    "引發": "causal",
    "導致": "causal",
    "促成": "causal",
    "促進": "causal",
    "促進參與": "causal",
    "傳承延續": "causal",
    "傳統延續": "causal",
    "傳遞知識": "causal",
    "禁止": "causal",
    "限制": "causal",
    "防治目標": "causal",
    "面臨問題": "causal",
    "干擾": "causal",
    "調節": "causal",
    "相互調節": "causal",
    "增加風險": "causal",
    "目的": "causal",
    "效益": "causal",
    "依據": "causal",

    # ─── creative（創作/設計/研發/教學）──────────
    "內容設計": "creative",
    "研發單位": "creative",
    "研發": "creative",
    "創作": "creative",
    "設計": "creative",
    "製作": "creative",
    "編寫": "creative",
    "演出": "creative",
    "主辦": "creative",
    "主辦單位": "creative",
    "舉辦": "creative",
    "舉辦單位": "creative",
    "主導": "creative",
    "主管機關": "creative",
    "主題": "creative",
    "公共標案": "creative",
    "產出": "creative",
    "產品": "creative",
    "推出商品": "creative",
    "應用": "creative",
    "應用產品": "creative",
    "使用": "creative",
    "使用菌種": "creative",
    "栽培基質": "creative",
    "技術": "creative",
    "測量工具": "creative",
    "學習工具": "creative",
    "課程": "creative",
    "課程內容": "creative",
    "教學": "creative",
    "研究領域": "creative",
    "研究對象": "creative",
    "研究方法": "creative",
    "數位化": "creative",
    "菇場經營": "creative",
    "人才培育": "creative",
    "文化實踐": "creative",
    "行動參與": "creative",

    # ─── documentary（紀錄/紀念/引用）────────────
    "紀念": "documentary",
    "記錄": "documentary",
    "記載": "documentary",
    "引用": "documentary",
    "出處": "documentary",
    "作者": "documentary",
    "導演": "documentary",
    "報導": "documentary",
    "拍攝": "documentary",
    "受訪": "documentary",
    "訪談": "documentary",
    "證實": "documentary",
    "冠軍": "documentary",
    "亞軍": "documentary",
    "得獎": "documentary",
    "相關": "documentary",
}


def map_node_group(node_group):
    if not node_group:
        return "其他"
    return NODE_GROUP_TO_META.get(node_group.strip(), "其他")


def map_link_label(label):
    if not label:
        return "其他"
    return LABEL_TO_META_RELATION.get(label.strip(), "其他")
